<div class="col-lg-4 col-sm-6 portfolio-item">
    <div class="card h-100">
        <a href="#"><img class="card-img-top" src="{$sorteos[a].img}" alt=""></a>
        <div class="card-body">
            <h4 class="card-title">
                <a href="#">{$sorteos[a].title}</a>
            </h4>
            <p class="card-text">{$sorteos[a].desc}</p>
        </div>
    </div>
</div>
<script src="<?= JAVASCRIPT_PATH ?>/views/index.js" type="text/javascript"></script>
