<!DOCTYPE html>
<head>
    <meta charset="UTF-8" />
    <title><?= VERSION ?> - </title>
    <?= $this->headlink(); ?>
    <script type="text/javascript"> window.adblockEnabled = true; </script>
</head>
<body >
    <?php
       (CONFIG == 'AOS06') ? $prod=TRUE : $prod=false; 
    ?>
    <nav class="navbar navbar-expand-lg navbar-dark bg-blue fixed-top">
            <div class="container">
                <a class="navbar-brand" href="#">{$title}</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Inicio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="row">
                <h1 class="my-4"><br>
                </h1>
            </div>  
            <div class="row">
                <div class="col-md-6">
                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- Adictos_alGYm -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-6064776652287686"
                         data-ad-slot="9944808138"
                         data-ad-format="auto"
                         data-full-width-responsive="true"></ins>
                    <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                </div>
                <div class="col-md-6">
                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- inicio -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-6064776652287686"
                         data-ad-slot="2850699014"
                         data-ad-format="auto"
                         data-full-width-responsive="true"></ins>
                    <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                </div>
            </div>
            <div class="row">
                {section name=a loop=$sorteos}
                    
                {/section}                
            </div>
            <ul class="pagination justify-content-center">
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">1</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">2</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">3</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            </ul>
        </div>
        <center>
            <ins class="adsbygoogle"
                style="display:block"
                data-ad-client="ca-pub-6064776652287686"
                data-ad-slot="7725767078"
                data-ad-format="auto"
                data-full-width-responsive="true"></ins>
           <script>
           (adsbygoogle = window.adsbygoogle || []).push({});
           </script>
        </center>
        <?= $this->headScript(); ?>
        <!-- <script type="text/javascript" src="../vendor/twitter/bootstrap/dist/js/bootstrap.js"></script> -->  
        <script type="text/javascript" src="adframe.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/sweetalert2@7.26.29/dist/sweetalert2.all.min.js"></script>
        <script type="text/javascript">
            if(window.adblockEnabled) {
                swal({
                    allowOutsideClick: false,
                    confirmButton:false,
                    title: '¡Ayuda!',
                    imageUrl: '../app/resources/img/adblock.png',
                    text: 'Esta pagina vive gracias a la publicidad, deshabilita adblock y ayudanos a segir mejorando, la pagina no funcionara mientras este activado adblock',
                    confirmButtonText: 'Entendido'
                });
            }
        </script>
</body>
</html>
